In [4]:
import numpy as np

arr = np.array([10,20,30,40])

copy = arr.copy()

copy[3]=51

print(arr)
print()
print(copy)

[10 20 30 40]

[10 20 30 51]


In [5]:
import numpy as np

arr = np.array([10,20,30,40])

view = arr.view()

view[3]=51

print(arr)
print()
print(copy)

[10 20 30 51]

[10 20 30 51]
