# where

In [4]:
import numpy as np

arr = np.array([1,2,3,8,8,9,5,2,4,6,4])

ans = np.where(arr==4)

rem_zero = np.where((arr%3) == 0)

print(ans)
print()
print(rem_zero)

(array([ 8, 10], dtype=int64),)

(array([2, 5, 9], dtype=int64),)


# searchsorted

In [13]:
import numpy as np

arr = np.array([1,2,3,4,4,6,7,7,8,9])

ans = np.searchsorted(arr, 5)
group = np.searchsorted(arr, [5,2,7])


print(ans)
print()
print(group)

5

[5 1 6]


# sort

In [15]:
import numpy as np

arr = np.array([1,2,3,8,8,9,5,2,4,6,4])
arr2 = np.array(['a','v','m','l','k'])

print(np.sort(arr))
print()
print(np.sort(arr2))

[1 2 2 3 4 4 5 6 8 8 9]

['a' 'k' 'l' 'm' 'v']


# Filter

In [17]:
import numpy as np

arr = np.array(['a','v','m','l','k'])

f=[True,False,True,True,False]

filtered_array = arr[f]

print(filtered_array)

['a' 'm' 'l']


# shuffle

In [20]:
import numpy as np
arr = np.array([1,2,3,8,4,6])

np.random.shuffle(arr)
print(arr)



[6 1 8 3 4 2]


# unique

In [22]:
import numpy as np
arr = np.array([1,2,3,8,8,9,5,2,4,6,4])

new_arr= np.unique(arr)

print(new_arr)

[1 2 3 4 5 6 8 9]


# Resize

In [23]:
import numpy as np
arr = np.array([1,2,3,8,8,9,5,2,4,6,4,3])

new_array = np.resize(arr, (3,4))
print(new_array)

[[1 2 3 8]
 [8 9 5 2]
 [4 6 4 3]]
