In [2]:
import numpy as np
arr = np.array([1,2,3,4])

new_array = np.add(arr,3)
print(new_array)

[4 5 6 7]


In [4]:
import numpy as np
arr = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])

new_array = np.add(arr,arr2)
print(new_array)

[5 5 5 5]


In [7]:
import numpy as np
arr = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])

new_array = np.subtract(arr,arr2)
print(new_array)

[-3 -1  1  3]


In [9]:
import numpy as np
arr = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])

new_array = np.multiply(arr,arr2)
print(new_array)

[4 6 6 4]


In [11]:
import numpy as np
arr = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])

new_array = np.divide(arr,arr2)
print(new_array)

[0.25       0.66666667 1.5        4.        ]


In [12]:
import numpy as np
arr = np.array([1,2,3,4])
arr2 = np.array([4,3,2,1])

new_array = np.add(arr,arr2)
print(new_array)

[5 5 5 5]


## 2D arrray arithmetic operation

In [14]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

print(arr)
print()
print(arr2)
print()

new_array = np.add(arr,arr2)
print(new_array)

[[1 2 3 4]
 [5 6 7 8]]

[[1 2 3 4]
 [5 6 7 8]]

[[ 2  4  6  8]
 [10 12 14 16]]


In [16]:
import numpy as np
var = np.mod(5,3)

print(var)

2


## reciprocal(1/a)

In [18]:
import numpy as np
arr = np.array([1,2,3,4])

new_array = np.reciprocal(arr)

print(new_array)

[1 0 0 0]
