In [8]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2= np.array([5,6,7,8])

print(arr1)
print(arr2)
print()

np.concatenate([arr1,arr2])


[1 2 3 4]
[5 6 7 8]



array([1, 2, 3, 4, 5, 6, 7, 8])

# stack two arrays vertically and horizontally


In [15]:

import numpy as np

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Method 1:
np.concatenate([a, b], axis=0) #vertically

# Method 2:
np.vstack([a, b])  #vertically

# Method 3:
np.r_[a, b]  #vertically



array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
import numpy as np

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

# Method 1:
np.concatenate([a, b], axis=1) #horizontally

# Method 2:
np.hstack([a, b])  #horizontally

# Method 3:
np.c_[a, b]  #horizontally



array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])