## Zero_Array

In [1]:
import numpy as np
zeroArray=np.zeros(5)
zeroArray

array([0., 0., 0., 0., 0.])

## one_Array

In [2]:
import numpy as np
oneArray = np.ones([4,3])
oneArray

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Eye Array

In [3]:
import numpy as np
arr = np.eye(4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## set_diagonal element using diag function

In [8]:
import numpy as np
arr2= np.diag([3,6,7])
print(np.diag(arr2))
print("\n")
print(arr2)

[3 6 7]


[[3 0 0]
 [0 6 0]
 [0 0 7]]


## random number generate with max,min,and total values

In [38]:
import numpy as np
arr = np.random.randint(3,9,6)
arr

array([6, 4, 7, 8, 8, 8])

## random number generate between 0 and 1

In [36]:
import numpy as np
arr = np.random.rand(2,3)
arr

array([[0.4543757 , 0.89930504, 0.38307286],
       [0.9099233 , 0.9006465 , 0.00388887]])

## randn()
## used to generate value that are close to zero(negative and positive)

In [10]:
import numpy as np
arr = np.random.randn(3)
arr

array([-0.85615445, -1.22904237, -0.26319282])

## ranf()
## generate random values with intervals [0.0,1.0)

In [14]:
import numpy as np
arr = np.random.ranf(10)
arr

array([0.09531466, 0.83000438, 0.19096784, 0.39583477, 0.36993068,
       0.56656916, 0.7254482 , 0.47838994, 0.93887866, 0.78925866])

## Range function

In [12]:
import numpy as np
arr = np.arange(2,5)
arr

array([2, 3, 4])