In [7]:
import numpy as np
arr = np.array([[1,2,3,4],[7,5,3,8]])

new_array = np.array(arr,ndmin=4)

print(arr)
print()
print(arr.shape)
print()
print(arr.ndim)

print()
print()

print(new_array)
print()
print(new_array.shape)
print()
print(new_array.ndim)

[[1 2 3 4]
 [7 5 3 8]]

(2, 4)

2


[[[[1 2 3 4]
   [7 5 3 8]]]]

(1, 1, 2, 4)

4


# reshape

In [18]:
import numpy as np
arr = np.array([1,2,3,7,5,3,8,7])

reshape_array= arr.reshape(4,2)
print(reshape_array)
print()
print(reshape_array.ndim)


[[1 2]
 [3 7]
 [5 3]
 [8 7]]

2


# 1D to 3D

In [21]:
import numpy as np
arr = np.array([1,2,3,7,5,3,8,7,9,10,11,12])

reshape_array= arr.reshape(2,3,2)
print(reshape_array)
print()
print(reshape_array.ndim)

# again converting 1D

one = reshape_array.reshape(-1)
print()
print(one)
print(one.ndim)


[[[ 1  2]
  [ 3  7]
  [ 5  3]]

 [[ 8  7]
  [ 9 10]
  [11 12]]]

3

[ 1  2  3  7  5  3  8  7  9 10 11 12]
1
